Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # Create a public network, which generally matched to bridged network.
  #config.vm.network "public_network"
  config.vm.network "forwarded_port", guest:8080, host:8080, auto_correct: true
  
  # Share an additional folder to the guest VM.
   config.vm.synced_folder "./www", "/var/www/html/"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

  # Docker Provisioner
  config.vm.provision "docker" do |d|
   d.pull_images "httpd"
   d.run "apache", image: "httpd", args: " -v /var/www/html/:/usr/local/apache2/htdocs/ -p 8080:80 --restart=always"
  end


end