Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.hostname = "mydatabase"

  config.vm.provision "shell", path: "provision.sh"
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx-mca"
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  
  config.vm.network "public_network", ip: "192.168.1.99"
end
