Vagrant.configure("2") do |config|
  config.vm.define "db" do |db| 
    db.vm.box = "hashicorp/precise32"
    db.vm.hostname = "mysql"

    db.vm.provision "shell", path: "provision.sh"
    db.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx-mca"
    db.vm.network "forwarded_port", guest: 3306, host: 3306
    db.vm.network "forwarded_port", guest: 443, host: 8443


    db.vm.network "public_network", ip: "192.168.1.99"
  end

  config.vm.define "web" do |web| 
    web.vm.box = "hashicorp/precise32"
    web.vm.hostname = "client"
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    web.vm.network "public_network", ip: "192.168.1.88"
  end
end